from PIL import Image, ImageTk

#Colores
#FRAME PRINCIPAL
COLOR_FONDO = "white" #f1faff

#NO SE DE DONDE ES
COLOR_BOTON_CURSOR_ENCIMA = "#38a2eb" #CAMBIAR
COLOR_BOTON_CURSOR_FUERA = "#2f88c5" #CAMBIAR
### MENU ###
#AJUSTES DEL MENU
ANCHO_MENU = 140
ALTO_MENU = 20
MITAD_MENU = 10
WIDTH_LOGO = 25
HEIGHT_LOGO = 25
#COLORES MENU Y SUB MENU
COLOR_BARRA_SUPERIOR = "#5D6363"
#MENU
COLOR_MENU_LATERAL = "#6F6F6F"
COLOR_MENU_CURSOR_ENCIMA = "#2f88c5"
#SUBMENU
COLOR_SUBMENU_LATERAL = "#959595"
COLOR_SUBMENU_CURSOR_ENCIMA = "#38a2eb"

#SECCION EN PROCESO

COLOR_GUARDAR = "#"
COLOR_LIMPIAR = "#"
COLOR_EDITAR = "#"
COLOR_ELIMINAR = "#"
COLOR_FG = "#6F6F6F"
COLOR_BG = "#"
COLOR_HOVER = "#535353"
COLOR_TEXTO = "white"





