from PIL import Image, ImageTk

#Colores
COLOR_BARRA_SUPERIOR = "#535353"
COLOR_MENU_LATERAL = "#6F6F6F"
COLOR_SUBMENU_LATERAL = "#959595"
COLOR_CUERPO_PRINCIPAL = "#f1faff"
COLOR_MENU_CURSOR_ENCIMA = "#2f88c5"
COLOR_SUBMENU_CURSOR_ENCIMA = "#38a2eb"

COLOR_BOTON_CURSOR_ENCIMA = "#38a2eb" #CAMBIAR
COLOR_BOTON_CURSOR_FUERA = "#2f88c5" #CAMBIAR

#MENU
ANCHO_MENU = 140
ALTO_MENU = 20

WIDTH_LOGO = 25
HEIGHT_LOGO = 25


COLOR_GUARDAR = "#"
COLOR_LIMPIAR = "#"
COLOR_EDITAR = "#"
COLOR_ELIMINAR = "#"
COLOR_FG = "#6F6F6F"
COLOR_BG = "#"
COLOR_HOVER = "#535353"
COLOR_TEXTO = "white"





